version: '3'
services:
  redis:
    image: "redis/redis-stack-server:latest"
    ports:
      - "6379:6379"
    volumes:
      - database:/data/db
  worker:
    build: .
    command: sh -c "npm install && npm run downloader"
    environment: # LIST OF ENV VARS
      - REDIS_HOST=redis
    ports: # LIST OF PORTS MAPPED
      - '7001:7001'
    working_dir: /app
    volumes:
      - ./:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./downloads:/opt/music
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - worker
volumes:
  database:
