version: '3'
services:
  redis:
    container_name: database
    image: "redis/redis-stack-server:latest"
    ports:
      - "6379:6379"
    volumes:
      - database:/data/db
  app:
    container_name: app
    image: node:18.18.0-slim
    command: sh -c "npm install && npm run build && npm start"
    environment: # LIST OF ENV VARS
      - REDIS_HOST=redis
    ports: # LIST OF PORTS MAPPED
      - '3000:3000'
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - redis
  downloader:
    container_name: downloader
    build:
      context: ./
      dockerfile: ./src/workers/downloader/Dockerfile
    environment: # LIST OF ENV VARS
      - REDIS_HOST=redis
    volumes:
      - downloads:/app/downloads
    depends_on:
      - redis
  nginx:
    container_name: web
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./downloads:/opt/music
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  ngrok:
    container_name: tunnel
    image: ngrok/ngrok:latest
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    depends_on:
      - nginx
volumes:
  database:
  downloads:
